version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: echo ${HOME}
      - run:
          command: ls -la ${HOME}
      - run:
          command: echo ${MAPS_KEY_FILE}>${HOME}/src/main/res/values/google_maps_api.xml
      - run:
          command: ./gradlew build
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex "./.*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit